language: go

dist: bionic

os: linux

go:
  - '1.12'

before_script:
  - sudo sysctl -w net.ipv4.ip_forward=1

services:
  - docker

env:
  global:
    - GO111MODULE=on
    - CGO_ENABLED=0
    - GO_VERSION=1.12
    - HELM_VERSION=v3.1.2

install:
  - wget https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -O /tmp/helm.tar.gz
  - tar xzf /tmp/helm.tar.gz -C /tmp --strip-components=1
  - chmod +x /tmp/helm

script:
  - /tmp/helm template ./deploy/helm-chart/kubernetes-replicator/.
  - /tmp/helm lint ./deploy/helm-chart/kubernetes-replicator/
  - curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish --rm-dist
  - bash ./scripts/bump-app-version.sh

before_deploy:
  - docker login -u "${DOCKER_LOGIN_USERNAME}" -p "${DOCKER_LOGIN_PASSWORD}" "${DOCKER_LOGIN_URL}"
  - export FULL_IMAGE="${DOCKER_LOGIN_URL}/mittwald/kubernetes-replicator"
deploy:
  - provider: script
    cleanup: false
    script: >-
      curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish --rm-dist &&
      docker push "${FULL_IMAGE}:latest" &&
      docker push "${FULL_IMAGE}-arm64:latest" &&
      docker push "${FULL_IMAGE}-armv5:latest" &&
      docker push "${FULL_IMAGE}-armv6:latest" &&
      docker push "${FULL_IMAGE}-armv7:latest"
    on:
      tags: false
      branch: master
      condition: $TRAVIS_OS_NAME = linux
  - provider: script
    cleanup: false
    script: >-
      curl -sL https://git.io/goreleaser | bash -s -- --rm-dist &&
      bash ./scripts/bump-app-version.sh publish
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
