apiVersion: v1
appVersion: "1.0.0-alpha1"
description: Controller for replicating secrets+configmaps across namespaces
name: kubernetes-replicator
version: 0.1.0
url: https://github.com/mittwald/kubernetes-replicator
