name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.RELEASE_USER_TOKEN }}
        days-before-stale: 14

        stale-issue-message: >
          There has not been any activity to this issue in the last 14 days.
          It will automatically be closed after 7 more days. Remove the `stale` label to prevent this.
        stale-issue-label: 'stale'
        exempt-issue-labels: 'confirmed,help-wanted'

        stale-pr-message: >
          There has not been any activity to this pull request in the last 14 days.
          It will automatically be closed after 7 more days. Remove the `stale` label to prevent this.
        stale-pr-label: 'stale'
        exempt-pr-labels: 'awaiting-approval,work-in-progress'
